# config/packages/framework.yaml

framework:
    secret: '%env(APP_SECRET)%'
    session: true

    serializer:
        enabled: true
        default_context:
            circular_reference_handler: 'App\Serializer\CircularReferenceHandler'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
