#got it
api_login_check:
    path: /api/login_check
#got it
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST
#якщо це ендпоінт - то є
post_index:
    path: /api/posts
    controller: App\Controller\PostController::index
    methods: [ 'GET' ]

post_show:
    path: /api/posts/{id}
    controller: App\Controller\PostController::show
    methods: [ 'GET' ]
#є
post_create:
    path: /api/posts
    controller: App\Controller\PostController::create
    methods: [ 'POST' ]
#got it
post_update:
    path: /api/posts/{id}
    controller: App\Controller\PostController::update
    methods: [ 'PUT', 'PATCH' ]
#є
post_delete:
    path: /api/posts/{id}
    controller: App\Controller\PostController::delete
    methods: [ 'DELETE' ]


# Routes for CommentController
comment_get_comments_by_post:
    path: /api/posts/{postId}/comments
    controller: App\Controller\CommentController::getCommentsByPost
    methods: GET

comment_get_comment:
    path: /api/comments/{id}
    controller: App\Controller\CommentController::getComment
    methods: GET

comment_create_comment:
    path: /api/posts/{postId}/comments
    controller: App\Controller\CommentController::createComment
    methods: POST

comment_update_comment:
    path: /api/comments/{id}
    controller: App\Controller\CommentController::updateComment
    methods: [PUT, PATCH]

comment_delete_comment:
    path: /api/comments/{id}
    controller: App\Controller\CommentController::deleteComment
    methods: DELETE
    
api_posts_add_key_value_store:
    path: /api/posts/{id}/key_value_stores
    controller: App\Controller\PostController::addKeyValueStore
    methods: POST
    
api_posts_get_key_value_stores:
    path: /api/posts/{id}/key_value_stores
    controller: App\Controller\PostController::getKeyValueStore
    methods: GET
    
api_posts_delete_key_value_store:
    path: /api/posts/{postId}/key_value_stores/{id}
    controller: App\Controller\PostController::deleteKeyValueStore
    methods: DELETE
