# Existing routes for API endpoints

# Routes for UserController
api_admin_user_index:
    path: /api/admin/users
    controller: App\Controller\UserController::index
    methods: [GET]

api_admin_user_create:
    path: /api/admin/users/create
    controller: App\Controller\UserController::create
    methods: [POST]

# Other existing routes
api_login_check:
    path: /api/login_check

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [POST]

post_index:
    path: /api/posts
    controller: App\Controller\PostController::index
    methods: [GET]

post_show:
    path: /api/posts/{id}
    controller: App\Controller\PostController::show
    methods: [GET]

post_create:
    path: /api/posts
    controller: App\Controller\PostController::create
    methods: [POST]

post_update:
    path: /api/posts/{id}
    controller: App\Controller\PostController::update
    methods: [PUT, PATCH]

post_delete:
    path: /api/posts/{id}
    controller: App\Controller\PostController::delete
    methods: [DELETE]

comment_get_comments_by_post:
    path: /api/posts/{postId}/comments
    controller: App\Controller\CommentController::getCommentsByPost
    methods: [GET]

comment_get_comment:
    path: /api/comments/{id}
    controller: App\Controller\CommentController::getComment
    methods: [GET]

comment_create_comment:
    path: /api/posts/{postId}/comments
    controller: App\Controller\CommentController::createComment
    methods: [POST]

comment_update_comment:
    path: /api/comments/{id}
    controller: App\Controller\CommentController::updateComment
    methods: [PUT, PATCH]

comment_delete_comment:
    path: /api/comments/{id}
    controller: App\Controller\CommentController::deleteComment
    methods: [DELETE]

api_posts_add_key_value_store:
    path: /api/posts/{id}/key_value_stores
    controller: App\Controller\PostController::addKeyValueStore
    methods: [POST]

api_posts_get_key_value_stores:
    path: /api/posts/{id}/key_value_stores
    controller: App\Controller\PostController::getKeyValueStores
    methods: [GET]

api_posts_delete_key_value_store:
    path: /api/posts/{postId}/key_value_stores/{id}
    controller: App\Controller\PostController::deleteKeyValueStores
    methods: [DELETE]

# New routes for Twig templates
get_post_comments:
    path: /posts/{postId}/comments
    controller: App\Controller\CommentTemplateController::getCommentsByPost
    requirements:
        postId: '\d+'

get_comment:
    path: /comments/{id}
    controller: App\Controller\CommentTemplateController::getComment
    requirements:
        id: '\d+'

create_comment:
    path: /posts/{postId}/comments
    controller: App\Controller\CommentTemplateController::createComment
    methods: [POST]
    requirements:
        postId: '\d+'

update_comment:
    path: /comments/{id}
    controller: App\Controller\CommentTemplateController::updateComment
    methods: [PUT, PATCH]
    requirements:
        id: '\d+'

delete_comment:
    path: /comments/{id}
    controller: App\Controller\CommentTemplateController::deleteComment
    methods: [DELETE]
    requirements:
        id: '\d+'

posts_index:
    path: /posts
    controller: App\Controller\PostTemplateController::index
    methods: [GET]

posts_show:
    path: /posts/{id}
    controller: App\Controller\PostTemplateController::show
    methods: [GET]
    requirements:
        id: '\d+'

posts_create:
    path: /posts
    controller: App\Controller\PostTemplateController::create
    methods: [POST]

posts_update:
    path: /posts/{id}
    controller: App\Controller\PostTemplateController::update
    methods: [PUT, PATCH]
    requirements:
        id: '\d+'

posts_delete:
    path: /posts/{id}
    controller: App\Controller\PostTemplateController::delete
    methods: [DELETE]
    requirements:
        id: '\d+'

posts_add_key_value_store:
    path: /posts/{id}/key_value_stores
    controller: App\Controller\PostTemplateController::addKeyValueStore
    methods: [POST]
    requirements:
        id: '\d+'

posts_get_key_value_stores:
    path: /posts/{id}/key_value_stores
    controller: App\Controller\PostTemplateController::getKeyValueStores
    methods: [GET]
    requirements:
        id: '\d+'

posts_delete_key_value_store:
    path: /posts/{postId}/key_value_stores/{id}
    controller: App\Controller\PostTemplateController::deleteKeyValueStore
    methods: [DELETE]
    requirements:
        postId: '\d+'
        id: '\d+'

register:
    path: /register
    controller: App\Controller\RegistrationTemplateController::register
    methods: [GET, POST]
