controllers:
    resource: ../src/Controller/
    namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST
